# Generated by Django 2.2 on 2020-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to='core/uploads/'),
        ),
    ]
